# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:
  odh-imageresizer-core:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    build:
      context: .
      dockerfile: odh-imageresizer-core/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_S3BucketUrl: ${ODH_IMAGERESIZERCORE_S3}
    ports: 
      - "6005:80"
