version = 1
SPDX-PackageName = "odh-imageresizer-core"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/odh-imageresizer-core"

[[annotations]]
path = [".github/**", "infrastructure/**", ".gitignore", ".pre-commit-config.yaml", "LICENSE", "docker-compose.dcproj", ".env.example", ".dockerignore", "odh-imageresizer-core.sln", "odh-imageresizer-core/odh-imageresizer-core.csproj", "odh-imageresizer-core/**.json", "odh-imageresizer-core/Dockerfile"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"
